# Generated by Django 5.1.6 on 2025-02-13 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_stories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='video',
        ),
    ]
