# Generated by Django 5.1.6 on 2025-02-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_stories_image_remove_stories_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, to='posts.postimage'),
        ),
        migrations.AddField(
            model_name='stories',
            name='videos',
            field=models.ManyToManyField(blank=True, default=None, to='posts.postvideo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
