# Generated by Django 5.1.6 on 2025-02-13 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_stories_images_stories_videos_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.RemoveField(
            model_name='post',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='images',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='videos',
        ),
    ]
