# Generated by Django 5.1.6 on 2025-03-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_active',
            new_name='is_available',
        ),
        migrations.AddField(
            model_name='listing',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
