# Generated by Django 5.1.6 on 2025-03-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('shipped', 'Shipped')], default='pending', max_length=20),
        ),
    ]
